services:
  nexandria-graph:
    build: .
    container_name: nexandria-graph
    image: nexandria-graph:latest
    volumes:
      - /home/ubuntu/data:/tmp
    ports:
      - '8900:8000'
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - on-chain-feed-network
networks:
  on-chain-feed-network:
    name: on-chain-feed-network
    external: true